
-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color3 = '#7ac3ff'
local Color1 = '#fc50b4'
local Color6 = '#8a3868'
local Color8 = '#eb87b6'
local Color9 = '#652664'
local Color4 = '#FDFD96'
local Color5 = '#4fc8b7'
local Color0 = '#699dad'
local Color2 = '#ff0000'
local Color7 = '#24273a'

highlight('Comment', nil, Color0, 'italic')
highlight('Identifier', nil, Color1, nil)
highlight('Error', nil, Color2, nil)
highlight('Operator', nil, Color3, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Repeat', nil, Color4, nil)
highlight('Number', nil, Color5, nil)
highlight('TSCharacter', nil, Color5, nil)
highlight('String', nil, Color5, 'italic')
highlight('StatusLine', Color3, Color6, nil)
highlight('WildMenu', Color7, Color8, nil)
highlight('Pmenu', Color7, Color8, nil)
highlight('PmenuSel', Color8, Color6, nil)
highlight('PmenuThumb', Color7, Color8, nil)
highlight('Normal', Color7, Color8, nil)
highlight('Visual', Color9, nil, nil)
highlight('CursorLine', Color9, nil, nil)
highlight('ColorColumn', Color9, nil, nil)
highlight('SignColumn', Color7, nil, nil)
highlight('LineNr', nil, Color8, nil)
highlight('TabLine', Color7, Color8, nil)
highlight('TabLineSel', Color8, Color6, nil)
highlight('TabLineFill', Color7, Color8, nil)
highlight('TSPunctDelimiter', nil, Color8, nil)

link('TSFuncMacro', 'Macro')
link('TSProperty', 'TSField')
link('TSKeyword', 'Keyword')
link('TSField', 'Constant')
link('Conditional', 'Operator')
link('TSNumber', 'Number')
link('Operator', 'Keyword')
link('TSLabel', 'Type')
link('TSParameter', 'Constant')
link('TSParameterReference', 'TSParameter')
link('TSString', 'String')
link('TSTag', 'MyTag')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSPunctBracket', 'MyTag')
link('TSOperator', 'Operator')
link('TSRepeat', 'Repeat')
link('Folded', 'Comment')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSNamespace', 'TSType')
link('CursorLineNr', 'Identifier')
link('Whitespace', 'Comment')
link('TSFloat', 'Number')
link('NonText', 'Comment')
link('TSComment', 'Comment')
link('TSType', 'Type')
link('TSFunction', 'Function')
link('TSConditional', 'Conditional')
link('TSConstant', 'Constant')
link('Repeat', 'Conditional')
link('TelescopeNormal', 'Normal')
link('TSTagDelimiter', 'Type')
link('Macro', 'Function')
